import java.util.Random;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class BankAccount {

    public BankAccountInfo bankAccountInfo;
    public double balance;

    public class BankAccountInfo {

        private int accountNumber;
        private String firstName;
        private String lastName;

        public BankAccountInfo(int accountNumber, String firstName, String lastName) {
            this.accountNumber = accountNumber;
            this.firstName = firstName;
            this.lastName = lastName;
        }

        public int getAccountNumber() {
            return accountNumber;
        }

        public void setAccountNumber(int accountNumber) {
            this.accountNumber = accountNumber;
        }

        public String getFirstName() {
            return firstName;
        }

        public void setFirstName(String firstName) {
            this.firstName = firstName;
        }

        public String getLastName() {
            return lastName;
        }

        public void setLastName(String lastName) {
            this.lastName = lastName;
        }
    }

    private Random random = new Random();

    // Step 2
    public BankAccountInfo createAccount(String firstName, String lastName) {
        this.bankAccountInfo = new BankAccountInfo(random.nextInt(1000000), firstName, lastName);
        return this.bankAccountInfo;
    }

    // Step 4
    public Double deposit(Double amount) {
        this.balance += amount;
        return this.balance;
    }

    // Step 6
    public Double balance() {
        return this.balance;
    }

    // Step 8
    public Double withdraw(Double amount) throws Exception {
        // Step 10 (this code would appear only after step 9
        if (this.balance - amount < 0.0) {
            throw new Exception("Insufficient funds");
        }
        this.balance -= amount;
        return this.balance;
    }
}
